import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { listAgentFiles, readAgentFile, writeAgentFile } from '../src/storage/agent-files.js';

test('scoped agent roots browse and edit hidden credential, JSON, Markdown, and text files', async (t) => {
  const home = await mkdtemp(join(tmpdir(), 'agent-files-'));
  t.after(() => rm(home, { recursive: true, force: true }));
  const friday = join(home, '.friday');
  const fridayOptions = { root: 'friday', home, env: { ...process.env, FRIDAY_HOME: '' } };
  await mkdir(join(friday, 'nested'), { recursive: true });
  await writeFile(join(friday, 'nested', 'notes.md'), 'hello');
  await writeFile(join(friday, 'auth.json'), '{"token":"secret"}');
  await mkdir(join(friday, 'config'));
  await writeFile(join(friday, 'config', 'auth.json'), '{"key":"secret"}');
  await writeFile(join(friday, 'config', 'settings.json'), '{"model":"safe"}');
  await writeFile(join(friday, '.hidden'), 'hidden');
  await writeFile(join(friday, 'binary'), Buffer.from([0, 1]));
  await symlink(home, join(friday, 'escape'));
  const listing = await listAgentFiles(fridayOptions);
  assert.deepEqual(new Set(listing.entries.map((entry) => entry.name)), new Set(['.hidden', 'auth.json', 'binary', 'config', 'nested']));
  assert.equal(listing.entries.find((entry) => entry.name === 'auth.json').previewable, true);
  assert.equal(listing.entries.find((entry) => entry.name === 'auth.json').editable, true);
  const configFiles = await listAgentFiles({ ...fridayOptions, path: 'config' });
  assert.deepEqual(new Set(configFiles.entries.map((entry) => entry.name)), new Set(['auth.json', 'settings.json']));
  assert.ok(configFiles.entries.every((entry) => entry.editable));
  assert.deepEqual(Object.keys(listing), ['root', 'directory', 'path', 'entries']);
  assert.equal(listing.directory, friday);
  assert.equal(listing.entries[0].workspacePath, null);
  assert.equal((await readAgentFile({ ...fridayOptions, path: 'nested/notes.md' })).editorType, 'markdown');
  assert.equal((await readAgentFile({ ...fridayOptions, path: '.hidden' })).content, 'hidden');
  const settings = await readAgentFile({ ...fridayOptions, path: 'config/settings.json' });
  assert.equal(settings.content, '{"model":"safe"}');
  assert.equal(settings.editorType, 'json');
  assert.equal((await readAgentFile({ ...fridayOptions, path: 'config/auth.json' })).content, '{"key":"secret"}');
  await assert.rejects(readAgentFile({ ...fridayOptions, path: 'binary' }), /binary/);
  await assert.rejects(writeAgentFile({ ...fridayOptions, path: 'config/settings.json', content: '{bad json' }), /valid JSON/);
  await writeAgentFile({ ...fridayOptions, path: 'config/auth.json', content: '{"apiKey":"secret"}' });
  await writeAgentFile({ ...fridayOptions, path: 'config/settings.json', content: '{"model":"updated"}' });
  await writeAgentFile({ ...fridayOptions, path: 'nested/notes.md', content: '# Updated\n\n**Markdown**' });
  await writeAgentFile({ ...fridayOptions, path: '.hidden', content: 'updated text' });
  assert.equal((await readAgentFile({ ...fridayOptions, path: 'config/auth.json' })).content, '{"apiKey":"secret"}');
  assert.equal((await readAgentFile({ ...fridayOptions, path: 'config/settings.json' })).content, '{"model":"updated"}');
  assert.equal((await readAgentFile({ ...fridayOptions, path: 'nested/notes.md' })).content, '# Updated\n\n**Markdown**');
  assert.equal((await readAgentFile({ ...fridayOptions, path: '.hidden' })).content, 'updated text');
  await assert.rejects(listAgentFiles({ ...fridayOptions, path: '../' }));
  await assert.rejects(listAgentFiles({ ...fridayOptions, path: 'escape' }));
});

test('Pi root honors PI_CODING_AGENT_DIR parent', async (t) => {
  const home = await mkdtemp(join(tmpdir(), 'agent-pi-'));
  const parent = join(home, 'custom');
  await mkdir(join(parent, 'agent'), { recursive: true });
  t.after(() => rm(home, { recursive: true, force: true }));
  const data = await listAgentFiles({ root: 'pi', home, env: { PI_CODING_AGENT_DIR: join(parent, 'agent') } });
  assert.equal(data.root, 'pi');
  assert.deepEqual(data.entries.map((entry) => entry.name), ['agent']);
});
